branches:
  only:
  - master
  - develop

before_install:
  - openssl genrsa -out .private.key 2048
  - openssl rsa -in .private.key -out .public.key -pubout -outform PEM

language: node_js
node_js:
  - 10
  - 11
  - 12

services:
  - mongodb

script:
  - npm run lint
  - npm run test